#!/usr/bin/env bash

main() {
  script="https://github.com/fenv-org/ft/releases/download/v0.2.0-alpha.2/flutter_test.ts"
  if [[ "$(is_online)" == "online" ]]; then
    reload_arg="--reload=$script"
  else
    reload_arg=""
  fi
  <DENO_EXE_PLACEHOLDER >-A $reload_arg \
    "$script" "$@"
}

is_online() {
  if [[ "$(uname)" == "Darwin" ]]; then
    # macOS version
    if nc -G 1 -z 8.8.8.8 53 &>/dev/null; then
      echo "online"
    else
      echo "offline"
    fi
  else
    # Linux version
    if nc -w 1 -z 8.8.8.8 53 &>/dev/null; then
      echo "online"
    else
      echo "offline"
    fi
  fi
}

main "$@"
