name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get version from flutter_test.ts
        id: get-version
        run: |
          version=$(grep -A1 '\.name("ft")' flutter_test.ts | grep -o '".*"' | tail -n1 | tr -d '"')
          echo "version=$version" >> $GITHUB_OUTPUT
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is-prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "is-prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Update template with release URL
        run: |
          release_url="https://github.com/fenv-org/ft/releases/download/v${{ steps.get-version.outputs.version }}"
          sed -i "s|<TYPESCRIPT_PLACEHOLDER>|$release_url|g" ft-template
          git add ft-template
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update template with release URL for v${{ steps.get-version.outputs.version }}"
          git push

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: v${{ steps.get-version.outputs.version }}
          prerelease: ${{ steps.get-version.outputs.is-prerelease }}
          target_commitish: release
          token: ${{ github.token }}
